"""HTML generation for research synthesis results."""

from datetime import datetime
from pathlib import Path
from typing import Optional

from jinja2 import Environment, FileSystemLoader, select_autoescape

from knowledgeweaver.config import settings
from knowledgeweaver.processing.insight_generator import GeneratedInsights
from knowledgeweaver.processing.synthesizer import SynthesisResult
from knowledgeweaver.utils.logger import logger


class HTMLGenerator:
    """Generates interactive HTML reports from synthesis results."""

    def __init__(self):
        """Initialize HTML generator."""
        self.logger = logger
        self.output_dir = Path(settings.output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        query: str,
        synthesis: SynthesisResult,
        insights: GeneratedInsights,
        domain: str = "General",
    ) -> str:
        """Generate HTML report from synthesis results.

        Args:
            query: Original user query
            synthesis: Synthesis result
            insights: Generated insights
            domain: Research domain

        Returns:
            Path to generated HTML file
        """
        try:
            # Create HTML content
            html_content = self._build_html(query, synthesis, insights, domain)

            # Save to file
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"research_{timestamp}.html"
            filepath = self.output_dir / filename

            filepath.write_text(html_content, encoding="utf-8")
            self.logger.info(f"Generated HTML report: {filepath}")

            return str(filepath)

        except Exception as e:
            self.logger.error(f"Error generating HTML: {e}")
            raise

    def _build_html(
        self,
        query: str,
        synthesis: SynthesisResult,
        insights: GeneratedInsights,
        domain: str,
    ) -> str:
        """Build HTML content.

        Args:
            query: User query
            synthesis: Synthesis result
            insights: Generated insights
            domain: Research domain

        Returns:
            HTML content
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Build expandable sections
        synthesis_section = self._build_expandable_section(
            "Synthesis",
            synthesis.synthesis,
            "synthesis",
        )

        insights_section = self._build_insights_section(insights)
        connections_section = self._build_expandable_section(
            "Key Connections",
            "\n".join([f"• {c}" for c in synthesis.connections]),
            "connections",
        )

        citations_section = self._build_citations_section(synthesis.citations)

        # Build HTML
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Research Synthesis: {query}</title>
    <style>
{self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Research Synthesis Report</h1>
            <div class="metadata">
                <p><strong>Query:</strong> {query}</p>
                <p><strong>Domain:</strong> {domain}</p>
                <p><strong>Generated:</strong> {timestamp}</p>
            </div>
        </header>

        <main>
            {synthesis_section}
            {insights_section}
            {connections_section}
            {citations_section}
        </main>

        <footer>
            <div class="rating-section">
                <h3>Was this helpful?</h3>
                <div class="rating-widget">
                    <div class="stars">
                        <span class="star" data-rating="1">★</span>
                        <span class="star" data-rating="2">★</span>
                        <span class="star" data-rating="3">★</span>
                        <span class="star" data-rating="4">★</span>
                        <span class="star" data-rating="5">★</span>
                    </div>
                    <textarea id="feedback" placeholder="Optional feedback..."></textarea>
                    <button onclick="submitRating()">Submit Rating</button>
                </div>
            </div>
            <p class="footer-text">Generated by KnowledgeWeaver</p>
        </footer>
    </div>

    <script>
{self._get_javascript()}
    </script>
</body>
</html>"""

        return html

    def _build_expandable_section(self, title: str, content: str, section_id: str) -> str:
        """Build an expandable section.

        Args:
            title: Section title
            content: Section content
            section_id: Section ID

        Returns:
            HTML for expandable section
        """
        return f"""
        <section class="expandable-section">
            <button class="section-toggle" onclick="toggleSection('{section_id}')">
                <span class="toggle-icon">▶</span> {title}
            </button>
            <div id="{section_id}" class="section-content" style="display: none;">
                <p>{content}</p>
            </div>
        </section>"""

    def _build_insights_section(self, insights: GeneratedInsights) -> str:
        """Build insights section.

        Args:
            insights: Generated insights

        Returns:
            HTML for insights section
        """
        insights_html = "\n".join(
            [f"<li>{insight}</li>" for insight in insights.insights]
        )

        future_html = "\n".join(
            [f"<li>{direction}</li>" for direction in insights.future_directions]
        )

        questions_html = "\n".join(
            [f"<li>{question}</li>" for question in insights.open_questions]
        )

        return f"""
        <section class="insights-section">
            <h2>Key Insights</h2>
            <div class="insights-grid">
                <div class="insight-box">
                    <h3>Insights</h3>
                    <ul>{insights_html}</ul>
                </div>
                <div class="insight-box">
                    <h3>Future Directions</h3>
                    <ul>{future_html}</ul>
                </div>
                <div class="insight-box">
                    <h3>Open Questions</h3>
                    <ul>{questions_html}</ul>
                </div>
            </div>
        </section>"""

    def _build_citations_section(self, citations: list[str]) -> str:
        """Build citations section.

        Args:
            citations: List of citations

        Returns:
            HTML for citations section
        """
        if not citations:
            return ""

        citations_html = "\n".join(
            [f"<li>{citation}</li>" for citation in citations[:10]]
        )

        return f"""
        <section class="citations-section">
            <h2>Key Citations</h2>
            <ol>{citations_html}</ol>
        </section>"""

    def _get_css(self) -> str:
        """Get embedded CSS.

        Returns:
            CSS content
        """
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            min-height: 100vh;
            padding: 20px;
        }

        .container {
            max-width: 900px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 10px 40px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }

        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px 30px;
        }

        header h1 {
            font-size: 2.5em;
            margin-bottom: 20px;
        }

        .metadata {
            font-size: 0.95em;
            opacity: 0.95;
        }

        .metadata p {
            margin: 8px 0;
        }

        main {
            padding: 40px 30px;
        }

        section {
            margin-bottom: 30px;
        }

        h2 {
            color: #667eea;
            margin-bottom: 15px;
            font-size: 1.8em;
        }

        h3 {
            color: #764ba2;
            margin-bottom: 10px;
        }

        .expandable-section {
            border: 1px solid #e0e0e0;
            border-radius: 8px;
            margin-bottom: 15px;
            overflow: hidden;
        }

        .section-toggle {
            width: 100%;
            padding: 15px;
            background: #f5f5f5;
            border: none;
            cursor: pointer;
            font-size: 1.1em;
            text-align: left;
            transition: background 0.3s;
        }

        .section-toggle:hover {
            background: #efefef;
        }

        .toggle-icon {
            display: inline-block;
            transition: transform 0.3s;
            margin-right: 10px;
        }

        .section-toggle.active .toggle-icon {
            transform: rotate(90deg);
        }

        .section-content {
            padding: 20px;
            background: #fafafa;
            border-top: 1px solid #e0e0e0;
        }

        .insights-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
        }

        .insight-box {
            background: #f9f9f9;
            border-left: 4px solid #667eea;
            padding: 20px;
            border-radius: 8px;
        }

        .insight-box ul {
            list-style: none;
            padding-left: 0;
        }

        .insight-box li {
            margin: 10px 0;
            padding-left: 20px;
            position: relative;
        }

        .insight-box li:before {
            content: "→";
            position: absolute;
            left: 0;
            color: #667eea;
        }

        .citations-section ol {
            padding-left: 20px;
        }

        .citations-section li {
            margin: 10px 0;
            line-height: 1.5;
        }

        footer {
            background: #f5f5f5;
            padding: 30px;
            border-top: 1px solid #e0e0e0;
        }

        .rating-section {
            background: white;
            padding: 20px;
            border-radius: 8px;
            border: 1px solid #e0e0e0;
            margin-bottom: 20px;
        }

        .rating-section h3 {
            margin-bottom: 15px;
        }

        .rating-widget {
            display: flex;
            flex-direction: column;
            gap: 15px;
        }

        .stars {
            display: flex;
            gap: 10px;
            font-size: 2em;
        }

        .star {
            cursor: pointer;
            color: #ddd;
            transition: color 0.2s;
        }

        .star:hover,
        .star.active {
            color: #ffc107;
        }

        #feedback {
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px;
            font-family: inherit;
            resize: vertical;
            min-height: 80px;
        }

        button {
            background: #667eea;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1em;
            transition: background 0.3s;
        }

        button:hover {
            background: #764ba2;
        }

        .footer-text {
            text-align: center;
            color: #999;
            font-size: 0.9em;
            margin-top: 20px;
        }

        @media (max-width: 768px) {
            header h1 {
                font-size: 1.8em;
            }

            main {
                padding: 20px;
            }

            .insights-grid {
                grid-template-columns: 1fr;
            }

            .stars {
                font-size: 1.5em;
            }
        }
        """

    def _get_javascript(self) -> str:
        """Get embedded JavaScript.

        Returns:
            JavaScript content
        """
        return """
        let currentRating = 0;

        function toggleSection(sectionId) {
            const section = document.getElementById(sectionId);
            const button = event.target.closest('.section-toggle');
            section.style.display = section.style.display === 'none' ? 'block' : 'none';
            button.classList.toggle('active');
        }

        document.querySelectorAll('.star').forEach(star => {
            star.addEventListener('click', function() {
                currentRating = this.dataset.rating;
                document.querySelectorAll('.star').forEach(s => {
                    s.classList.remove('active');
                    if (s.dataset.rating <= currentRating) {
                        s.classList.add('active');
                    }
                });
            });

            star.addEventListener('mouseover', function() {
                document.querySelectorAll('.star').forEach(s => {
                    s.classList.remove('active');
                    if (s.dataset.rating <= this.dataset.rating) {
                        s.classList.add('active');
                    }
                });
            });
        });

        document.querySelector('.stars').addEventListener('mouseleave', function() {
            document.querySelectorAll('.star').forEach(s => {
                s.classList.remove('active');
                if (s.dataset.rating <= currentRating) {
                    s.classList.add('active');
                }
            });
        });

        function submitRating() {
            const feedback = document.getElementById('feedback').value;
            const data = {
                rating: currentRating,
                feedback: feedback,
                timestamp: new Date().toISOString()
            };
            console.log('Rating submitted:', data);
            alert('Thank you for your feedback!');
        }

        // Expand first section by default
        const firstToggle = document.querySelector('.section-toggle');
        if (firstToggle) {
            firstToggle.click();
        }
        """
